server:
  port: 8001
spring:
  application:
    name: authenticationserver
  datasource:
    password:
    username:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'
