server:
  port: 8001
spring:
  application:
    name: authenticationserver
  datasource:
    password: cK2AN6WkeajfFXJi
    username: coc
    url: jdbc:mysql://localhost:3306/coc
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
management:
  endpoints:
    web:
      exposure:
        include: '*'
